name: Hello

on: 
    push:
        branches: [main]

jobs:
    greet:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v3

            - name: hello print
              run: echo "Hello from Github Actions!" 

            - name: print the current date and time
              run: date

            - name: print trigger branch name
              run: echo "Triggered by branch:" ${{ github.ref_name }}

            - name: print username which triggered the workflow
              run: echo "Triggered by branch:" ${{ github.actor }}
            
            - name: print event name which triggered the workflow
              run: echo "Triggered by branch:" ${{ github.event_name }}
              
            - name: list files in the repository
              run: ls -la

            - name: print the runners operating system
              run: echo "Running on OS:" {{ runner.os}}

            - name: print exit code or misspell 
              run: exit 1