name: PR Check

on:
    pull_request: 
        branches:
            - main
        types: [opened, updated]

jobs:
    pr-check:
        runs-on: ubuntu-latest
        steps:
            - name: print branch  name
              run: echo "PR check running for branch:" ${{ github.head_ref }}
