name: PR Check

on:
    pull_request: 
        branches:
            - main
        types: [opened, synchronize]
    schedule:
        - cron: '0 0 * * *'

jobs:
    pr-check:
        runs-on: ubuntu-latest
        steps:
            - name: print branch  name
              run: echo "PR check running for branch:" ${{ github.ref_name }}
